name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: What is the problem the feature request solves?
      description: Please describe how feature request improves the Comet.
      placeholder: >
        A clear and concise description of what the improvement is. Ex. I'm always frustrated when [...]
        (This section helps Comet developers understand the context and *why* for this feature, in addition to the *what*)
  - type: textarea
    attributes:
      label: Describe the potential solution
      placeholder: >
        A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Additional context
      placeholder: >
        Add any other context or screenshots about the feature request here.
