# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: PR Build

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "doc/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "**.md"
  # manual trigger
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  linux-rust-test:
    name: Rust test (amd64)
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: nightly
          jdk-version: ${{env.JAVA_VERSION}}

      - uses: actions/checkout@v4
      - name: Rust test steps
        uses: ./.github/actions/rust-test

  linux-java-test:
    name: Java test (amd64)
    runs-on: ubuntu-latest
    container:
      image: amd64/rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: nightly
          jdk-version: ${{env.JAVA_VERSION}}
          architecture: x64

      - uses: actions/checkout@v4
      - name: Java test steps
        uses: ./.github/actions/java-test


  macos-rust-test:
    name: Rust test (macos)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: nightly
          jdk-version: ${{env.JAVA_VERSION}}
          architecture: x64

      - uses: actions/checkout@v4
      - name: Rust test steps
        uses: ./.github/actions/rust-test

  macos-java-test:
    name: Java test (macos)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: nightly
          jdk-version: ${{env.JAVA_VERSION}}
          architecture: x64

      - uses: actions/checkout@v4
      - name: Java test steps
        uses: ./.github/actions/java-test

  macos-aarch64-rust-test:
    name: Rust test (macos-aarch64)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: nightly
          jdk-version: ${{env.JAVA_VERSION}}
          architecture: aarch64

      - uses: actions/checkout@v4
      - name: Rust test steps
        uses: ./.github/actions/rust-test

  macos-aarch64-java-test:
    name: Java test (macos-aarch64)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust & Java toolchain
        uses: ./.github/actions/setup-macos-builder
        with:
          rust-version: nightly
          jdk-version: ${{env.JAVA_VERSION}}
          architecture: aarch64

      - uses: actions/checkout@v4
      - name: Java test steps
        uses: ./.github/actions/java-test
